import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

// import FormWithHookForm from "../components/FormWithHookForm";
import FormInputMultiCheckbox from "../components/FormInputMultiCheckbox";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {/* <FormWithHookForm /> */}
        <FormInputMultiCheckbox />
      </main>
    </div>
  );
};

export default Home;
