import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

// import MultiTextfields from "../components/MultiTextfields";
// import MultiCheckboxes from "../components/MultiCheckboxes";
// import FromBlogDemo from "../components/FromBlogDemo";
import MultiTextfieldsValidations from "../components/MultiTextfieldsValidations";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {/* <MultiTextfields /> */}
        {/* <MultiCheckboxes /> */}
        {/* <FromBlogDemo /> */}
        <MultiTextfieldsValidations />
      </main>
    </div>
  );
};

export default Home;
